### ISSUE TITLE
Compound Bower component

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery#6]
There's a possibility to have a compound `bower.json` with all iptools Bower components and their latest versions. The question is, would there be a use-case for having all iptools components installed at once?

Cc @beroes @GeorgMeyer23 @davidyezsetz

**Comment by davidyezsetz** [comment]
I doubt it. Especially since this is a growing library I don't see the need for a whole-sale installation

**Comment by ain** [comment]
Thanks for your 2 cents @davidyezsetz. @beroes, @GeorgMeyer23?

**Comment by GeorgMeyer23** [comment]
Same for me, no need to get the whole package.
Perhaps, if possible, a yeoman generator where you can select the tools you need would be useful.

**Comment by ain** [comment]
Majority vote: no compund Bower component.
